#!/usr/bin/env node
// motion-apply.js — `pingfusi motion apply-sampled <name> <motion-id>`: replay the item's
// SAMPLED tracks into the clone as a small self-contained WAAPI player.
//
// The sampled tier's middle step. `motion sample` (harness/motion-sampler.js) recorded
// the live page's motion as sampled-tier tracks in targets/<name>/motion-doc.json —
// computed values at uniform VIRTUAL-time offsets, fps receipted in provenance.source.
// This command turns that record into the clone's own animation implementation:
// clone/motion-replay.js, bound by selector and started per the track's trigger
// semantics (load → immediately; scroll-triggered → an IntersectionObserver on the item's
// scope). The replay is TIME-BASED: a site animating px-per-rAF-frame was recorded
// honestly at the declared fps, and the WAAPI replay NORMALIZES that frame-rate
// dependence — receipted in the player's header, never hidden.
//
// A CLIP IS NOT AN IMPLEMENTATION FOR ONGOING MOTION. A finite (settling) track replays
// as its verbatim clip — one pass, then RELEASE: fill "none" with an explicit onfinish
// that commits the final frame ONLY when no other writer owns the element, then cancels
// (a finished clip must never keep squatting on the element the way a permanent
// fill:"forwards" would — seen live: a 4s belt clip's forwards fill silently overrode a
// coexisting implementation forever). An ONGOING track (no settle observed — see the
// sampler's trackIsOngoing) is REFUSED as a clip: a clip that stops is a fabricated
// ending. It ships only when a lifted periodic-class fit (marquee) supplies the looping
// form, and then the player emits the LOOP — WAAPI iterations Infinity driven by the
// fit's velocity/direction, with the wrap distance measured from the element at RUNTIME
// (the duplicated-content scrollWidth/2 pattern), never from the clip.
//
// ONE OWNER. Before anything is written, an owner probe samples the target elements'
// inline style + computed transform for ~1s in the served clone (the kit's own replay
// held aside), each viewport group of elements SCROLLED INTO VIEW first — competing
// writers are commonly visibility-gated, and a probe watching from scroll 0 clears a
// belt whose writer paused off-screen (seen live). Any change means another
// implementation already writes those elements, and the apply REFUSES with a receipt
// naming the selector — resolving ownership is the operator's call, the kit never
// stacks implementations.
//
// This file is the CLONE'S animation implementation, not instrument contamination: the
// instrument doctrine ("never bake yourself into artifacts") bars the CAPTURE tooling
// from the clone; the replay IS the cloned motion, exactly like a hand-written
// fixes.js — generated so the sampled record stays the single source of truth.
//
// Idempotent by marker: the <script> tag lives between pingfusi:motion-replay markers in
// clone/index.html; a re-run replaces ONLY its own block, never other markup. Re-running
// for a second item regenerates motion-replay.js with every applied item's tracks, so no
// apply can silently drop another item's replay.
//
// Receipts for every intervention AND refusal: targets/<name>/motion/<id>/
// apply-sampled.json plus a workflow.jsonl entry; the player itself carries a header
// receipt (schema pingfusi/motion-replay@2, doc + track fingerprints). Item status →
// "applied-sampled" (NON-terminal): `pingfusi motion verify-sampled` owns the walk to
// "verified-sampled".
//
// Quarantine: only a DECLARED item may be applied — sweep candidates stay advisory, and
// nothing here runs on an ordinary clone.
//
// usage: pingfusi motion apply-sampled <name> <motion-id> [--attach <port|host:port>]
//          [--chrome <path>] [--headful]
"use strict";

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const cdp = require("./cdp.js");
const chrome = require("./chrome.js");
const motionDoc = require("./motion-doc.js");
const sampler = require("./motion-sampler.js");
const { serve } = require("./serve.js");
const { isDeclaredItem, readMotionDoc, readMotionItems, sampledTracksForItem, updateMotionItem } = require("./motion-items.js");

const WORK = process.cwd();
const PKG = path.resolve(__dirname, "..");
const VIA_PPK = process.env.PPK_ENTRY === "1";
const CMD = VIA_PPK ? "pingfusi" : "node harness/workflow.js";

const REPLAY_SCHEMA = "pingfusi/motion-replay@2";
// Every animation the generated player starts carries this id, so the kit's own replay
// is recognizable as ONE owner: the owner probe holds/cancels these before observing,
// and a clip's release-on-finish never mistakes a sibling kit track for a competitor.
const REPLAY_ANIM_ID = "pingfusi:motion-replay";
const MARKER_BEGIN = "<!-- pingfusi:motion-replay:begin — machine-owned block (generated by the build motion pass / `pingfusi motion apply-sampled`); re-running replaces this block only -->";
const MARKER_END = "<!-- pingfusi:motion-replay:end -->";
const MARKER_RE = /[ \t]*<!-- pingfusi:motion-replay:begin[\s\S]*?pingfusi:motion-replay:end -->/;
const NAV_TIMEOUT_MS = 30000;
const EVAL_TIMEOUT_MS = 15000;
// Wall milliseconds the owner probe watches the served clone for competing writers —
// PER viewport group: the probe scrolls each group of watched elements into view before
// watching (competing writers are commonly visibility-gated — a belt that only advances
// while its rail is on screen answered a scroll-0 probe with a false all-clear, seen
// live), so the wall budget is durationMs × groups, capped at OWNER_PROBE_MAX_GROUPS.
// Env-overridable for selftests; whatever ran rides in the receipt.
const OWNER_PROBE_MS = (() => {
  const raw = process.env.PPK_OWNER_PROBE_MS;
  const n = raw == null || raw === "" ? NaN : +raw;
  return Number.isFinite(n) && n > 0 ? n : 1000;
})();
const OWNER_PROBE_MAX_GROUPS = 5;

const die = (msg, code = 1) => { console.error(`✗ ${msg}`); process.exit(code); };
const firstLine = (e) => String((e && e.message) || e).split("\n")[0];
const sha16 = (value) => crypto.createHash("sha256").update(value).digest("hex").slice(0, 16);

// ── trigger → start semantics ───────────────────────────────────────────────────────────
// The samplable trigger vocabulary maps onto exactly two start semantics: "load" starts
// the animations immediately; every scroll-* trigger arms an IntersectionObserver on the
// most specific selector the declaration names (the trigger's own selector, else the
// item's scope, else the track's target). Anything else is refused by name — the sampler
// could never have recorded it, so a replay for it would be a fabrication.
function replayTrigger(raw, item) {
  const trigger = String(raw == null ? "load" : raw).trim() || "load";
  if (trigger === "load") return { raw: trigger, start: "load", observe: null };
  let selector = null;
  let m = /^scroll-to:(.+)$/.exec(trigger);
  if (m) selector = m[1];
  else if ((m = /^scroll-through:(.+)$/.exec(trigger))) {
    const parts = m[1].split("/");
    selector = parts.length >= 3 ? parts.slice(0, -2).join("/") : null;
  } else if (trigger !== "scroll-sweep") {
    throw new Error(`trigger "${trigger}" is not replayable — the sampled tier supports load, scroll-sweep, scroll-to:<selector>, and scroll-through:<selector>/<steps>/<dwellMs>`);
  }
  const scope = typeof item.scope === "string" && item.scope.trim() ? item.scope.trim() : null;
  return { raw: trigger, start: "scroll", observe: selector || scope };
}

// css property → WAAPI keyframe key ("transform" stays, "background-color" → backgroundColor)
function waapiProperty(property) {
  return String(property).replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

// ── clip vs loop: which form may implement this track? ──────────────────────────────────
// A finite (settling) track keeps its verbatim clip. An ONGOING track (ongoing:true on
// the record, re-derived from the keyframes either way — the evidence IS the keyframes)
// may only ship as a LOOP, and only a lifted periodic-class fit (marquee) can supply the
// looping form: velocity + direction from the fit, wrap distance from the element at
// runtime. Ongoing with no such fit is "unloopable" — the caller refuses it by name.
function replayMode(track) {
  const ongoing = track.ongoing === true || sampler.trackIsOngoing(track);
  if (!ongoing) return { ongoing: false, mode: "clip" };
  const fit = track.fit && track.fit.kind === "marquee" ? track.fit : null;
  const params = fit && fit.params && typeof fit.params === "object" ? fit.params : null;
  const velocity = params && typeof params.velocityPxPerSec === "number" && isFinite(params.velocityPxPerSec) && params.velocityPxPerSec > 0
    ? params.velocityPxPerSec : null;
  if (velocity && track.property === "transform") {
    return {
      ongoing: true, mode: "loop",
      axis: params.axis === "y" || params.channel === "ty" ? "y" : "x",
      velocityPxPerSec: velocity,
      direction: params.direction === -1 ? -1 : 1,
    };
  }
  return { ongoing: true, mode: "unloopable" };
}

// ── the generated player ────────────────────────────────────────────────────────────────
// Plain-data payload per item; the runtime below is deliberately tiny and dependency-free.
function replayPayload(item, tracks, trigger) {
  return {
    id: item.id,
    trigger: trigger.raw,
    start: trigger.start,
    observe: trigger.observe,
    tracks: tracks.map((track) => {
      const mode = replayMode(track);
      const base = { selector: track.target.selector, property: waapiProperty(track.property) };
      if (mode.mode === "loop") {
        // THE LOOP: the fit's motion law, never the clip — the clip is a finite window
        // onto motion that has no end, so only the law (velocity, direction) plus the
        // element's own runtime geometry can implement it.
        return { ...base, mode: "loop", axis: mode.axis, velocityPxPerSec: mode.velocityPxPerSec, direction: mode.direction };
      }
      return {
        ...base,
        mode: "clip",
        keyframes: track.keyframes.map((kf) => ({ offset: kf.offset, value: kf.value })),
        // The replay contract from the sampled record: duration = frames × stepMs of
        // VIRTUAL time; one pass, then release (fill "none" + onfinish, see the runtime).
        duration: track.timing.duration_ms,
        delay: track.timing.delay_ms || 0,
      };
    }),
  };
}

function trackReceipt(track) {
  const mode = replayMode(track);
  return {
    id: track.id,
    fingerprint16: motionDoc.trackFingerprint(track).slice(0, 16),
    selector: track.target.selector,
    property: track.property,
    mode: mode.mode,
    ...(mode.ongoing ? { ongoing: true } : {}),
    frames: track.keyframes.length,
    duration_ms: track.timing.duration_ms,
    source: (track.provenance && track.provenance.source) || null,
  };
}

function renderReplay(receipt, payloads) {
  return `/* ${REPLAY_SCHEMA} — GENERATED by the pingfusi motion machinery (the build motion
 * pass, or \`pingfusi motion apply-sampled\`); do not edit — a re-run regenerates.
 *
 * This file is the clone's animation implementation for sampled-tier motion: the live
 * page's computed values were read at uniform VIRTUAL-time steps (fps in each track's
 * source receipt) and are replayed here as time-based WAAPI keyframes. A frame-rate-
 * dependent site animation was recorded honestly at that declared fps; this time-based
 * replay NORMALIZES the frame-rate dependence — receipted, never hidden.
 *
 * Finite clips play once and RELEASE: fill "none", then an explicit onfinish commits the
 * final frame only when no other writer owns the element, and cancels — never a
 * permanent fill:"forwards" squat. Ongoing tracks play their fitted LOOP: iterations
 * Infinity at the fitted velocity, wrap distance measured from the element at runtime.
 *
 * receipt: ${JSON.stringify(receipt)}
 */
(() => {
  "use strict";
  const REPLAY_ID = ${JSON.stringify(REPLAY_ANIM_ID)};
  const ITEMS = ${JSON.stringify(payloads, null, 2)};
  const play = (track) => {
    let els = [];
    try { els = document.querySelectorAll(track.selector); } catch (e) { els = []; }
    for (const el of els) {
      try {
        if (track.mode === "loop") {
          // ONGOING motion loops by LAW, not by clip: velocity and direction come from
          // the fitted marquee; the wrap distance is measured from THIS element right now
          // (a duplicated-content belt recycles at half its scroll span), so the loop is
          // seamless on the clone's own geometry instead of frozen at the recording's.
          const span = track.axis === "y" ? el.scrollHeight : el.scrollWidth;
          const dist = span / 2;
          if (!(dist > 0) || !(track.velocityPxPerSec > 0)) continue;
          const fn = track.axis === "y" ? "translateY" : "translateX";
          const loop = el.animate(
            [
              { offset: 0, [track.property]: fn + "(0px)" },
              { offset: 1, [track.property]: fn + "(" + (track.direction * dist) + "px)" },
            ],
            { duration: (dist / track.velocityPxPerSec) * 1000, iterations: Infinity, easing: "linear", fill: "none" }
          );
          loop.id = REPLAY_ID;
          continue;
        }
        // FINITE clip: one pass, then RELEASE. fill "none" plus an explicit onfinish
        // that commits the final frame ONLY when no other writer owns the element
        // (another non-replay animation, or an inline value already present), then
        // cancels — a finished clip must never keep squatting on the element.
        // Default-on pass extension: a clip may carry EXACT engine parameters read
        // verbatim from the page's own declaration (gsap/waapi tiers) — iterations
        // (possibly "infinite"), direction, per-keyframe easing. Absent fields keep
        // the sampled-clip defaults, so apply-sampled payloads replay unchanged. An
        // infinite clip never finishes, so it takes no release handler.
        const iterations = track.iterations === "infinite" ? Infinity
          : typeof track.iterations === "number" && track.iterations > 0 ? track.iterations : 1;
        const clip = el.animate(
          track.keyframes.map((kf) => Object.assign(
            { offset: kf.offset, [track.property]: kf.value },
            kf.easing ? { easing: kf.easing } : null
          )),
          { duration: track.duration, delay: track.delay, iterations, direction: track.direction || "normal", fill: "none" }
        );
        clip.id = REPLAY_ID;
        if (iterations === Infinity) continue;
        clip.onfinish = () => {
          try {
            const last = track.keyframes.length ? track.keyframes[track.keyframes.length - 1].value : null;
            const others = (typeof el.getAnimations === "function" ? el.getAnimations() : [])
              .filter((a) => a !== clip && String(a.id || "").indexOf(REPLAY_ID) !== 0);
            const inline = el.style ? el.style[track.property] : "";
            if (last != null && !others.length && !inline) el.style[track.property] = last;
          } catch (e) {}
          try { clip.cancel(); } catch (e) {}
        };
      } catch (e) {}
    }
  };
  const arm = (item) => {
    if (item.start !== "scroll" || !item.observe || typeof IntersectionObserver !== "function") {
      for (const track of item.tracks) play(track);
      return;
    }
    let roots = [];
    try { roots = document.querySelectorAll(item.observe); } catch (e) { roots = []; }
    if (!roots.length) { for (const track of item.tracks) play(track); return; }
    const io = new IntersectionObserver((entries) => {
      if (entries.some((entry) => entry.isIntersecting)) {
        io.disconnect();
        for (const track of item.tracks) play(track);
      }
    });
    for (const root of roots) io.observe(root);
  };
  const armAll = () => { for (const item of ITEMS) arm(item); };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", armAll);
  else armAll();
  // PHASE-FREEZE hook (measurement contract, LEARNINGS #38): before the measurement
  // capture, pxFreezeAnimations calls every registered hook so kit players freeze their
  // OWN writers at phase 0 — the pixel gates must compare both sides at a fixed
  // animation phase. This player's writers are WAAPI, so freezing is pause + seek to
  // the active start (progress 0). A future non-WAAPI kit player must register the same
  // contract or its subtree is honestly excluded as unfreezable.
  const freezeAtPhase0 = () => {
    let anims = [];
    try { anims = typeof document.getAnimations === "function" ? document.getAnimations() : []; } catch (e) { anims = []; }
    const out = { player: "motion-replay", frozen: 0, ids: [] };
    for (const a of anims) {
      if (!a || String(a.id || "").indexOf(REPLAY_ID) !== 0) continue;
      try {
        a.pause();
        let t0 = 0;
        try { const t = a.effect && a.effect.getComputedTiming ? a.effect.getComputedTiming() : null; if (t && typeof t.delay === "number" && isFinite(t.delay)) t0 = t.delay; } catch (e) {}
        a.currentTime = t0;
        out.frozen++;
        if (out.ids.length < 50) out.ids.push(String(a.id));
      } catch (e) {}
    }
    return out;
  };
  if (typeof window !== "undefined") (window.__pingfusiFreezeHooks = window.__pingfusiFreezeHooks || []).push(freezeAtPhase0);
})();
`;
}

// Replace this command's OWN marker block, or add one before </body> — other markup is
// never touched. Returns { html, action } so the receipt can say which happened.
function injectScriptTag(html) {
  const block = `${MARKER_BEGIN}\n<script src="motion-replay.js" defer></script>\n${MARKER_END}`;
  if (MARKER_RE.test(html)) return { html: html.replace(MARKER_RE, block), action: "replaced" };
  const at = html.toLowerCase().lastIndexOf("</body>");
  if (at >= 0) return { html: `${html.slice(0, at)}${block}\n${html.slice(at)}`, action: "inserted" };
  return { html: `${html}\n${block}\n`, action: "appended" };
}

// ── the owner probe: ONE implementation per element ─────────────────────────────────────
// Serve the clone, hold the kit's OWN replay aside (motion-replay.js is renamed for the
// probe's duration so a previously applied player cannot trip its own gate; the in-page
// probe additionally cancels any REPLAY_ANIM_ID animation each tick), then watch the
// target elements' inline style + computed transform for ~1s of wall time. Any change is
// another implementation writing the element.
async function ownerProbe(name, dir, selectors, opts) {
  const replayFile = path.join(dir, "clone", "motion-replay.js");
  const holdFile = `${replayFile}.owner-probe-hold`;
  const held = fs.existsSync(replayFile);
  if (held) fs.renameSync(replayFile, holdFile);
  let server = null;
  let acq = null;
  try {
    let target = {};
    try { target = JSON.parse(fs.readFileSync(path.join(dir, "target.json"), "utf8")); } catch (_) {}
    let liveSnap = null;
    try { liveSnap = JSON.parse(fs.readFileSync(path.join(dir, "live.json"), "utf8")); } catch (_) {}
    const viewport = chrome.resolveViewport({ target, live: liveSnap });
    server = serve(name, 0);
    await new Promise((resolve) => server.on("listening", resolve));
    const url = `http://127.0.0.1:${server.address().port}/`;
    acq = await chrome.acquire({
      attach: opts.attach, chromePath: opts.chrome, headless: !opts.headful,
      width: viewport.width, height: 1050,
    });
    const { session, targetId } = await cdp.openPage(acq.port, { host: acq.host });
    try {
      await chrome.normalizeViewport(session, viewport);
      await cdp.navigate(session, url, { timeoutMs: NAV_TIMEOUT_MS, warn: () => {} });
      const probe = await chrome.probeEnvironment(session);
      if (!probe.verdict.ok) {
        // A throttled/hidden page freezes exactly the competing writers this probe
        // exists to see — observing there would fake an all-clear.
        throw new Error(`environment refused on the clone page: ${probe.verdict.reason}${opts.headful ? "" : " — re-run with --headful"}`);
      }
      const captureSource = fs.readFileSync(path.join(PKG, "tools", "browser-capture.js"), "utf8");
      await cdp.evaluate(session, captureSource, { awaitPromise: false });
      // The probe watches durationMs PER viewport group (it scrolls each group of
      // elements into view first — the vantage the player will run from), so the eval
      // budget covers the full group walk.
      const ret = await cdp.evaluate(session, `pxOwnerProbe(${JSON.stringify({ selectors, durationMs: OWNER_PROBE_MS, maxGroups: OWNER_PROBE_MAX_GROUPS })})`, { timeoutMs: OWNER_PROBE_MS * OWNER_PROBE_MAX_GROUPS + EVAL_TIMEOUT_MS });
      if (!ret || typeof ret !== "object" || !Array.isArray(ret.changed)) {
        throw new Error(`pxOwnerProbe returned ${JSON.stringify(ret == null ? null : ret).slice(0, 80)} — tools/browser-capture.js changed shape?`);
      }
      if (Array.isArray(ret.unwatched) && ret.unwatched.length) {
        // An element the probe never observed is an element it cannot clear — a partial
        // watch must not become a fake all-clear.
        throw new Error(`owner probe could not watch ${ret.unwatched.length} element(s) beyond ${OWNER_PROBE_MAX_GROUPS} viewport group(s) (first: ${ret.unwatched[0].selector}) — apply items separately or narrow their scopes`);
      }
      return { url, replayHeld: held, ...ret };
    } finally {
      session.close();
      await cdp.closeTab(acq.port, targetId, { host: acq.host });
    }
  } finally {
    if (server) server.close();
    if (acq) await acq.cleanup();
    if (held && fs.existsSync(holdFile)) fs.renameSync(holdFile, replayFile);
  }
}

// ── main ────────────────────────────────────────────────────────────────────────────────
function parseArgs(argv) {
  const a = {};
  const rest = [];
  for (let i = 0; i < argv.length; i++) {
    const v = argv[i];
    if (v === "--attach") a.attach = argv[++i];
    else if (v === "--chrome") a.chrome = argv[++i];
    else if (v === "--headful") a.headful = true;
    else if (v.startsWith("--")) die(`unknown flag ${v} — usage: ${CMD} motion apply-sampled <name> <motion-id> [--attach <port>] [--chrome <path>] [--headful]`, 2);
    else rest.push(v);
  }
  a.name = rest[0];
  a.id = rest[1];
  return a;
}

async function main(argv = process.argv.slice(2)) {
  const args = parseArgs(argv);
  const { name, id } = args;
  if (!name || !id) die(`usage: ${VIA_PPK ? "pingfusi motion apply-sampled" : "node harness/motion-apply.js"} <name> <motion-id> [--attach <port>] [--chrome <path>] [--headful]`, 2);

  const dir = path.join(WORK, "targets", name);
  let manifest;
  try { manifest = readMotionItems(dir); }
  catch (error) { die(`targets/${name}/motion-items.json: ${error.message}`, 2); }
  const item = manifest.items.find((candidate) => candidate.id === id);
  if (!manifest.exists || !item) die(`targets/${name}/motion-items.json has no item "${id}"`, 2);
  if (!isDeclaredItem(item)) {
    // The quarantine line: applying motion to the clone is enforcement work, and
    // enforcement is opt-in by declaration.
    die(`motion item ${id} was never operator-declared — applying only runs on owned receipts; adopt it by recording owner provenance on the item in targets/${name}/motion-items.json (e.g. \"declaredBy\": \"manual\")`, 2);
  }

  const liveRead = readMotionDoc(dir);
  if (!liveRead.doc) {
    die(`targets/${name}/motion-doc.json ${liveRead.exists ? "is unreadable" : "is missing"} — the sampled record lives there; acquire it first: ${CMD} motion sample ${name} ${id}`);
  }
  const tracks = sampledTracksForItem(item, liveRead.doc);
  if (!tracks.length) {
    die(`motion item ${id} has no sampled tracks in targets/${name}/motion-doc.json — sample the live page first: ${CMD} motion sample ${name} ${id}`);
  }
  if (Array.isArray(item.sampledTrackIds) && item.sampledTrackIds.length && tracks.length < item.sampledTrackIds.length) {
    const found = new Set(tracks.map((track) => String(track.id)));
    const missing = item.sampledTrackIds.filter((trackId) => !found.has(String(trackId)));
    die(`motion item ${id} names sampled track(s) the doc no longer holds: ${missing.join(", ")} — the record drifted; re-sample: ${CMD} motion sample ${name} ${id}`);
  }

  const indexFile = path.join(dir, "clone", "index.html");
  if (!fs.existsSync(indexFile)) {
    die(`no targets/${name}/clone/index.html to attach the replay to — build the clone first: ${CMD} capture-build ${name}`);
  }

  let trigger;
  try { trigger = replayTrigger(item.trigger, item); }
  catch (error) { die(error.message); }

  // Refusals from here on are receipted — they are dispositions of the item, not
  // argument errors.
  const failWithReceipt = (reason, extra = {}) => {
    const receiptFile = path.join(dir, "motion", id, "apply-sampled.json");
    fs.mkdirSync(path.dirname(receiptFile), { recursive: true });
    fs.writeFileSync(receiptFile, JSON.stringify({
      schema: "pingfusi/motion-apply-sampled@1",
      at: new Date().toISOString(),
      target: name, item: id, ok: false, reason, ...extra,
    }, null, 2) + "\n");
    console.error(`✗ ${reason}`);
    console.error(`  receipt: ${path.relative(WORK, receiptFile)}`);
    process.exit(1);
  };

  // The player carries EVERY applied item's tracks, so applying item B never silently
  // drops item A's replay from the shared file. The current item joins the set now.
  const included = [];
  for (const candidate of manifest.items) {
    if (candidate.id === id || !isDeclaredItem(candidate)) continue;
    if (!["applied-sampled", "verified-sampled"].includes(String(candidate.status || "").toLowerCase())) continue;
    const candidateTracks = sampledTracksForItem(candidate, liveRead.doc);
    if (!candidateTracks.length) continue;
    let candidateTrigger;
    try { candidateTrigger = replayTrigger(candidate.trigger, candidate); } catch (_) { continue; }
    included.push({ item: candidate, tracks: candidateTracks, trigger: candidateTrigger });
  }
  included.push({ item, tracks, trigger });

  // ── RULE: A CLIP IS NOT AN IMPLEMENTATION FOR ONGOING MOTION ──────────────────────────
  // Every ongoing track in the regenerated player (this item's AND every other applied
  // item's — the file is shared) must have its looping form; a one-shot clip would play
  // its window and freeze, which is not the motion that was recorded.
  const unloopable = [];
  for (const entry of included) {
    for (const track of entry.tracks) {
      const mode = replayMode(track);
      if (mode.mode === "unloopable") unloopable.push({ item: entry.item.id, track: track.id, selector: track.target.selector, property: track.property });
    }
  }
  if (unloopable.length) {
    const first = unloopable[0];
    failWithReceipt(
      `ongoing motion with no periodic fit — trace longer, or declare the loop form. ` +
      `${first.selector} ${first.property} (item ${first.item}) never settled inside the sampled window, so a one-shot clip would glide through its window and freeze — that is not the recorded motion. ` +
      `A lifted marquee fit supplies the looping form: re-run ${CMD} motion sample ${name} ${first.item} with more --frames (a longer trace lets the periodic class win), or declare the loop explicitly.`,
      { unloopable }
    );
  }

  // ── RULE: ONE OWNER — probe for competing writers before writing anything ─────────────
  const probeSelectors = [...new Set(included.flatMap((entry) => entry.tracks.map((track) => track.target.selector)))];
  let probe;
  try {
    probe = await ownerProbe(name, dir, probeSelectors, args);
  } catch (error) {
    die(`owner probe failed before apply: ${firstLine(error)}`);
  }
  if (probe.changed.length) {
    const first = probe.changed[0];
    failWithReceipt(
      `another implementation owns ${first.selector} — its ${first.prop} changed during the ${OWNER_PROBE_MS}ms owner probe (${JSON.stringify(first.from)} → ${JSON.stringify(first.to)} at +${first.atMs}ms) with the kit's own replay held aside. ` +
      `The kit never stacks implementations: resolve ownership first (remove the competing writer from the clone, or drop this declaration), then re-run ${CMD} motion apply-sampled ${name} ${id}.`,
      { ownerProbe: { durationMs: OWNER_PROBE_MS, elements: probe.elements, replayHeld: probe.replayHeld, changed: probe.changed, missing: probe.missing, groups: probe.groups, scrolled: probe.scrolled } }
    );
  }

  const now = new Date().toISOString();
  const headerReceipt = {
    schema: REPLAY_SCHEMA,
    at: now,
    target: name,
    doc: { file: `targets/${name}/motion-doc.json`, sha256_16: sha16(JSON.stringify(liveRead.doc)) },
    items: included.map((entry) => ({
      id: entry.item.id,
      trigger: entry.trigger.raw,
      tracks: entry.tracks.map(trackReceipt),
    })),
  };
  const replaySource = renderReplay(headerReceipt, included.map((entry) => replayPayload(entry.item, entry.tracks, entry.trigger)));
  const replayFile = path.join(dir, "clone", "motion-replay.js");
  fs.writeFileSync(replayFile, replaySource);

  const injected = injectScriptTag(fs.readFileSync(indexFile, "utf8"));
  fs.writeFileSync(indexFile, injected.html);

  const trackReceipts = tracks.map(trackReceipt);
  const loops = trackReceipts.filter((t) => t.mode === "loop").length;
  const receipt = {
    schema: "pingfusi/motion-apply-sampled@1",
    at: now,
    target: name,
    item: id,
    trigger: trigger.raw,
    start: trigger.start,
    doc: headerReceipt.doc,
    ownerProbe: {
      durationMs: OWNER_PROBE_MS, elements: probe.elements, ticks: probe.ticks,
      replayHeld: probe.replayHeld, missing: probe.missing, changed: [],
      groups: probe.groups, scrolled: probe.scrolled,
    },
    replay: {
      file: `targets/${name}/clone/motion-replay.js`,
      sha256_16: sha16(replaySource),
      bytes: Buffer.byteLength(replaySource),
      itemsIncluded: included.map((entry) => entry.item.id),
    },
    html: { file: `targets/${name}/clone/index.html`, scriptTag: injected.action },
    tracks: trackReceipts,
    ok: true,
  };
  const receiptFile = path.join(dir, "motion", id, "apply-sampled.json");
  fs.mkdirSync(path.dirname(receiptFile), { recursive: true });
  fs.writeFileSync(receiptFile, JSON.stringify(receipt, null, 2) + "\n");

  updateMotionItem(dir, id, {
    status: "applied-sampled", // NON-terminal by design: verify-sampled owns the walk to verified-sampled
    appliedSampledAt: now,
    applyReceipt: path.relative(WORK, receiptFile),
  });
  try {
    const wf = require("./workflow.js");
    wf.appendLedger(name, {
      ts: now, event: "motion-apply-sampled", phase: null, runId: wf.runId(), gate: null, forced: false,
      item: id,
      reason: `replayed ${tracks.length} sampled track(s) into clone/motion-replay.js (${loops} loop(s), ${tracks.length - loops} clip(s); trigger ${trigger.raw}, owner probe clean over ${probe.elements} element(s), script tag ${injected.action})`,
    });
  } catch (error) { console.log(`  ⚠ workflow.jsonl receipt failed (apply unaffected): ${String((error && error.message) || error).split("\n")[0]}`); }

  console.log(`✓ applied-sampled — ${tracks.length} track(s) replayed as time-based WAAPI in targets/${name}/clone/motion-replay.js (${loops} looping by fitted law, ${tracks.length - loops} release-on-finish clip(s); script tag ${injected.action})`);
  console.log(`  owner probe: clean — no competing writer on ${probe.elements} element(s) over ${OWNER_PROBE_MS}ms${Array.isArray(probe.groups) && probe.groups.length ? ` × ${probe.groups.length} viewport group(s)${probe.scrolled ? ", scrolled into view" : ""}` : ""}`);
  console.log(`  receipt: ${path.relative(WORK, receiptFile)}`);
  console.log(`  item ${id} → status "applied-sampled" (non-terminal) — next: ${CMD} motion verify-sampled ${name} ${id}`);
}

if (require.main === module) {
  main().catch((error) => { console.error(`✗ ${firstLine(error)}`); process.exit(1); });
}
module.exports = {
  MARKER_BEGIN,
  MARKER_END,
  REPLAY_ANIM_ID,
  REPLAY_SCHEMA,
  injectScriptTag,
  main,
  ownerProbe,
  renderReplay,
  replayMode,
  replayTrigger,
  waapiProperty,
};
